export const DENNIS_NOTICE = 'Generated by Dennis AI — Review before use.';

export type DennisMode = 'Offline only' | 'Online only' | 'Hybrid';
export function placeholderDennisResponse(context: string) {
  return `This is a placeholder Dennis response for ${context}. Future versions will search approved documents and provide source-based answers.`;
}

export function safeSuggestion(action: string, moduleName: string) {
  return `${placeholderDennisResponse(moduleName)} Suggested ${action.toLowerCase()} text will remain a draft until an authorized user reviews and applies it.`;
}
export const dennisSafetyRules = [
  'Dennis can suggest, draft, explain, summarize, remind, and search; he does not make final compliance decisions.',
  'Dennis must not approve SOPs, authorize documents, close CAPA records, delete records, or modify permissions.',
  'Dennis must not change laboratory results or blood inventory without human confirmation and correct permission.',
  'Online Dennis is disabled by default and must not receive patient-identifiable or donor-identifiable information.'
];
