import { useMemo, useState, type ReactNode } from 'react';
import { AlertTriangle, Bell, Bot, FileSearch, Send, ShieldCheck, Sparkles } from 'lucide-react';
import { DENNIS_NOTICE, dennisSafetyRules, placeholderDennisResponse, safeSuggestion } from '../services/dennisService';

const tabs = ['Ask Dennis','Document Search','CAPA Helper','Audit Helper','Report Writer','Quality Indicator Analyst','Training Helper','Blood Bank Quality Assistant','Risk Assistant','Equipment Assistant','Inventory and Supplier Assistant','Dennis Alerts','Dennis Activity Log','Dennis Settings'] as const;
type Tab = typeof tabs[number];
type Msg = { role: 'user' | 'dennis'; content: string; sources?: string[] };

const helperButtons: Record<string, string[]> = {
  'CAPA Helper': ['Improve NC Description','Suggest Root Causes','Suggest Corrective Action','Suggest Preventive Action','Draft Follow-up Plan','Suggest Effectiveness Check'],
  'Audit Helper': ['Suggest Audit Questions','Suggest Evidence to Check','Summarize Finding','Draft Audit Report Section','Suggest Corrective Action'],
  'Training Helper': ['Explain SOP Simply','Generate Quiz','Suggest Competency Questions','Draft Training Summary','Identify Training Gaps'],
  'Blood Bank Quality Assistant': ['Summarize Expiring Blood Units','Draft Thursday-to-Thursday Handover','Summarize Adverse Donor Reactions','Draft Blood Bank NC','Draft Monthly Blood Bank Quality Report'],
  'Risk Assistant': ['Suggest Risks','Suggest Causes','Suggest Controls','Suggest Mitigation Actions','Draft Risk Summary'],
  'Equipment Assistant': ['Summarize Calibration Due','Draft Breakdown Report','Summarize Downtime','Draft Replacement Justification','Suggest PM Follow-up'],
  'Inventory and Supplier Assistant': ['Summarize Stock-out Risk','Summarize Expiry Alerts','Draft Purchase Justification','Draft Supplier Complaint','Summarize Supplier Performance']
};

function Notice() { return <div className="dennis-notice"><ShieldCheck size={14}/>{DENNIS_NOTICE}</div>; }
function OutputCard({ title, children }: { title: string; children: ReactNode }) { return <div className="dennis-output"><strong>{title}</strong><p>{children}</p><div className="source-box">Source area placeholder: approved/current SECH_LIMS documents and records will appear here in future phases.</div><Notice/></div>; }

function AskDennis() {
  const [input, setInput] = useState('');
  const [messages, setMessages] = useState<Msg[]>([{ role: 'dennis', content: placeholderDennisResponse('Ask Dennis'), sources: ['Approved document source placeholder'] }]);
  const send = () => { if (!input.trim()) return; setMessages(m => [...m, { role: 'user', content: input.trim() }, { role: 'dennis', content: placeholderDennisResponse('Ask Dennis'), sources: ['Source placeholder: title, version, section, status'] }]); setInput(''); };
  return <div className="dennis-grid two"><div className="card dennis-chat"><div className="chat-stream">{messages.map((m,i)=><div key={i} className={`chat-bubble ${m.role}`}><strong>{m.role==='dennis'?'Dennis':'You'}</strong><p>{m.content}</p>{m.role==='dennis'&&<><div className="source-box">{m.sources?.join(' · ')}</div><Notice/></>}</div>)}</div><div className="dennis-input"><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask Dennis a quality management question…"/><button onClick={send}><Send size={16}/> Send</button><button className="secondary" onClick={()=>setMessages([])}>Clear conversation</button></div></div><SafetyPanel/></div>;
}

function DocumentSearch() {
  const docs = ['SOPs','Policies','Manuals','Forms','Registers','Work instructions','Approved documents','Blood bank quality documents','Equipment documents','Safety documents','Internal audit documents'];
  return <div className="dennis-grid two"><div className="card"><h3><FileSearch size={18}/> Document Search</h3><input placeholder="Search approved/current documents (placeholder)…"/><div className="chip-row">{docs.map(d=><span className="badge" key={d}>{d}</span>)}</div><OutputCard title="Placeholder search result">Future versions will show source document title, version, section, status, and role-permitted content only.</OutputCard></div><SafetyPanel/></div>;
}
function Helper({ tab }: { tab: Tab }) { const [out,setOut]=useState('Select a Dennis action to generate a placeholder draft.'); return <div className="dennis-grid two"><div className="card"><h3><Sparkles size={18}/> {tab}</h3><textarea placeholder={`Paste ${tab} context here. Do not include patient or donor identifiers.`}/><div className="button-grid">{(helperButtons[tab]??[]).map(b=><button key={b} onClick={()=>setOut(safeSuggestion(b, tab))}>{b}</button>)}</div><OutputCard title="Dennis draft output">{out}</OutputCard></div><SafetyPanel/></div>; }
function ReportWriter() { const [out,setOut]=useState('Choose report parameters, then generate a placeholder draft.'); return <div className="dennis-grid two"><div className="card"><h3>Report Writer</h3><div className="form-grid"><select><option>Monthly quality report</option><option>Management review input</option><option>Blood bank quality report</option><option>CAPA summary report</option><option>Internal audit report</option><option>Equipment downtime report</option><option>Complaint summary report</option><option>Training summary report</option><option>Risk summary report</option><option>Supplier performance summary</option></select><input type="month"/><select><option>All modules</option><option>CAPA</option><option>Audit</option><option>Equipment</option><option>Inventory</option></select></div><button onClick={()=>setOut(placeholderDennisResponse('Report Writer draft report'))}>Generate placeholder draft</button><OutputCard title="Draft report placeholder">{out}</OutputCard></div><SafetyPanel/></div>; }
function IndicatorAnalyst() { const items=['Turnaround time','Sample rejection rate','Culture contamination rate','EQA performance','IQC failures','Equipment downtime','Complaint trends','CAPA closure rate','Stock-outs','Blood unit expiry','Reagent expiry','Internal audit finding trends']; return <div className="card"><h3>Quality Indicator Analyst</h3><div className="indicator-grid">{items.map(i=><OutputCard key={i} title={i}>{placeholderDennisResponse(i)}</OutputCard>)}</div></div>; }
function Alerts() { const alerts=['Overdue CAPA','SOP review due','Expired SOPs','Pending document approval','Calibration due','Maintenance due','EQA deadline','IQC failure follow-up','Expiring blood units','Expiring reagents','Expired staff competency','Pending internal audit actions','Management review due']; return <div className="card"><h3><Bell size={18}/> Dennis Alerts</h3><div className="alert-grid">{alerts.map((a,i)=><div className="alert-card" key={a}><strong>{a}</strong><span>Module: {i%2?'Documents':'Quality'}</span><span className="badge">{i%3?'Medium':'High'} priority</span><span>Due date: Placeholder</span><span>Responsible: Authorized role/person</span><span>Status: Mock alert</span><button className="secondary">Open module</button></div>)}</div></div>; }
function ActivityLog() { return <div className="card"><h3>Dennis Activity Log</h3><table><thead><tr><th>Date/time</th><th>User</th><th>Module</th><th>Action</th><th>AI mode</th><th>Status</th></tr></thead><tbody>{['Ask Dennis placeholder','CAPA suggestion placeholder','Settings viewed'].map((a,i)=><tr key={a}><td>Placeholder</td><td>Current user</td><td>Dennis</td><td>{a}</td><td>{i?'Offline placeholder':'Offline only'}</td><td>Draft</td></tr>)}</tbody></table></div>; }
function Settings() { return <div className="dennis-grid two"><div className="card"><h3>Dennis Settings</h3><label>Dennis mode<select defaultValue="Offline only"><option>Offline only</option><option>Online only</option><option>Hybrid</option></select></label><label><input type="checkbox" disabled/> Online Dennis enabled (disabled by default)</label><input type="password" placeholder="API key placeholder — not active in DENNIS-1" disabled/>{['Allow online Dennis for CAPA drafting','Allow online Dennis for audit reports','Allow online Dennis for management review reports','Allow online Dennis for training quizzes','Allow online Dennis for quality indicator summaries'].map(x=><label key={x}><input type="checkbox" disabled/> {x}</label>)}<div className="warning"><AlertTriangle size={18}/>Do not send patient names, patient IDs, donor IDs, phone numbers, addresses, or confidential personal information to online Dennis.</div><p className="muted">Dennis is an assistant. All Dennis outputs must be reviewed and approved by authorized personnel before use in official records.</p></div><SafetyPanel/></div>; }
function SafetyPanel(){return <div className="card"><h3><Bot size={18}/> Dennis safety workflow</h3>{dennisSafetyRules.map(r=><p className="safety-rule" key={r}>{r}</p>)}</div>}
export function DennisPage(){const [tab,setTab]=useState<Tab>('Ask Dennis'); const body=useMemo(()=>{ if(tab==='Ask Dennis')return <AskDennis/>; if(tab==='Document Search')return <DocumentSearch/>; if(tab==='Report Writer')return <ReportWriter/>; if(tab==='Quality Indicator Analyst')return <IndicatorAnalyst/>; if(tab==='Dennis Alerts')return <Alerts/>; if(tab==='Dennis Activity Log')return <ActivityLog/>; if(tab==='Dennis Settings')return <Settings/>; return <Helper tab={tab}/>;},[tab]); return <div className="page dennis-page"><div className="page-header"><div><p className="eyebrow">AI Quality Assistant · DENNIS-1</p><h2>Dennis</h2><p>Dennis helps users search, explain, draft, suggest, summarize, and remind. He is not a final decision-maker.</p></div></div><div className="tabbar dennis-tabs">{tabs.map(t=><button className={tab===t?'active':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div>{body}</div>}
