export const DENNIS_NOTICE = 'Generated by Dennis AI — Review before use.';

export function createDennisPlaceholder(action: string) {
  return {
    output: `This is a placeholder Dennis response for ${action}. Future phases will use approved SECH_LIMS records and configured offline/online AI workflows.`,
    notice: DENNIS_NOTICE,
    sources: [] as Array<{ title: string; version?: string; status?: string; section?: string }>,
    mode: 'offline-placeholder'
  };
}
