/**
 * Dennis AI engine helpers — dependency-free building blocks for the Dennis
 * Quality Assistant: document chunking, PII redaction, vector maths, and the
 * provider abstraction (local Ollama + optional online Anthropic/OpenAI/custom).
 *
 * Design constraints (offline-first desktop/LAN app):
 *  - No heavy/native dependencies. Providers are reached over HTTP with the
 *    built-in fetch, so the app installs and runs even when no model is present.
 *  - Every provider call is best-effort and times out; callers must degrade to
 *    document search (extractive answers) when a provider is unavailable.
 */

export const DENNIS_NOTICE = 'Generated by Dennis AI — Review before use.';

// ── Chunking ────────────────────────────────────────────────────────────────
export type Chunk = { text: string; index: number; heading: string | null; wordCount: number };

/**
 * Split extracted document text into ~500-1000 word chunks, preferring to break
 * on recognised section headings so each chunk stays topically coherent.
 */
export function chunkText(text: string, sections?: Array<{ heading: string; body: string }>, targetWords = 800): Chunk[] {
  const chunks: Chunk[] = [];
  let index = 0;
  const push = (heading: string | null, body: string) => {
    const words = body.trim().split(/\s+/).filter(Boolean);
    if (!words.length) return;
    for (let i = 0; i < words.length; i += targetWords) {
      const slice = words.slice(i, i + targetWords);
      chunks.push({ text: slice.join(' '), index: index++, heading, wordCount: slice.length });
    }
  };
  if (sections && sections.length) {
    for (const s of sections) push(s.heading || null, s.body || '');
    // Anything not captured by sections still needs indexing.
    if (!chunks.length && text.trim()) push(null, text);
  } else {
    push(null, text);
  }
  return chunks;
}

// ── Vector maths (semantic search, when embeddings are available) ────────────
export function cosineSim(a: number[], b: number[]): number {
  let dot = 0, na = 0, nb = 0;
  const n = Math.min(a.length, b.length);
  for (let i = 0; i < n; i++) { dot += a[i] * b[i]; na += a[i] * a[i]; nb += b[i] * b[i]; }
  if (!na || !nb) return 0;
  return dot / (Math.sqrt(na) * Math.sqrt(nb));
}

// ── PII redaction (before any online provider call) ──────────────────────────
export type Redaction = { redacted: string; replacements: Array<{ type: string; count: number }> };

const REDACTION_RULES: Array<{ type: string; placeholder: string; re: RegExp }> = [
  { type: 'EMAIL', placeholder: '[EMAIL]', re: /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b/g },
  // Ghana + international phone numbers and long digit runs (IDs/MRNs).
  { type: 'PHONE', placeholder: '[PHONE]', re: /(?:\+?\d[\d\s().-]{7,}\d)/g },
  { type: 'IDENTIFIER', placeholder: '[IDENTIFIER]', re: /\b(?:GHA[-\s]?\d{6,}|[A-Z]{2,4}-?\d{5,}|\d{9,})\b/g },
  { type: 'DOB', placeholder: '[DOB]', re: /\b(?:dob|date of birth)\b\s*[:=]?\s*\d{1,4}[/\-.]\d{1,2}[/\-.]\d{1,4}/gi },
];

/**
 * Mask common personal identifiers before sending text to an online AI. Name
 * detection is intentionally conservative (explicit "Patient/Donor name:" labels
 * only) because free-text name redaction is unreliable; the UI also warns the
 * user not to paste identifiers.
 */
export function redact(input: string): Redaction {
  let out = input ?? '';
  const replacements: Array<{ type: string; count: number }> = [];
  const count = (label: string, placeholder: string, re: RegExp) => {
    let n = 0;
    out = out.replace(re, () => { n++; return placeholder; });
    if (n) replacements.push({ type: label, count: n });
  };
  count('PATIENT_NAME', '[PATIENT_NAME]', /\b(?:patient|client)\s+name\s*[:=]\s*[^\n,;]{2,40}/gi);
  count('DONOR_ID', '[DONOR_ID]', /\bdonor\s*(?:id|number|no)\s*[:=]?\s*[A-Za-z0-9-]{3,}/gi);
  count('PATIENT_ID', '[PATIENT_ID]', /\b(?:patient|hospital|mrn|folder)\s*(?:id|no|number)?\s*[:=]?\s*[A-Za-z0-9-]{3,}/gi);
  for (const r of REDACTION_RULES) count(r.type, r.placeholder, r.re);
  return { redacted: out, replacements };
}

// ── Provider abstraction ──────────────────────────────────────────────────────
export type DennisProviderSettings = {
  localEnabled: boolean; localProvider: string; localEndpoint: string; localChatModel: string; localEmbedModel: string;
  onlineEnabled: boolean; onlineProvider: string; onlineEndpoint: string; onlineModel: string; onlineApiKey: string;
};
export type ChatMessage = { role: 'system' | 'user' | 'assistant'; content: string };

async function withTimeout<T>(p: Promise<T>, ms: number): Promise<T> {
  return await Promise.race([p, new Promise<T>((_, rej) => setTimeout(() => rej(new Error('Provider request timed out')), ms))]);
}

// ---- Local provider (Ollama-compatible) ----
export async function localChat(s: DennisProviderSettings, messages: ChatMessage[]): Promise<string> {
  const url = `${s.localEndpoint.replace(/\/$/, '')}/api/chat`;
  const r = await withTimeout(fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ model: s.localChatModel, messages, stream: false }) }), 60000);
  if (!r.ok) throw new Error(`Local AI error ${r.status}`);
  const data: any = await r.json();
  return data?.message?.content ?? data?.response ?? '';
}
export async function localEmbed(s: DennisProviderSettings, texts: string[]): Promise<number[][]> {
  const url = `${s.localEndpoint.replace(/\/$/, '')}/api/embeddings`;
  const out: number[][] = [];
  for (const t of texts) {
    const r = await withTimeout(fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ model: s.localEmbedModel, prompt: t }) }), 60000);
    if (!r.ok) throw new Error(`Local embedding error ${r.status}`);
    const data: any = await r.json();
    out.push(data?.embedding ?? []);
  }
  return out;
}

// ---- Online provider (Anthropic / OpenAI-compatible / custom) ----
export async function onlineChat(s: DennisProviderSettings, system: string, user: string): Promise<string> {
  if (!s.onlineApiKey) throw new Error('Online AI API key is not configured.');
  const provider = (s.onlineProvider || 'anthropic').toLowerCase();
  if (provider === 'anthropic') {
    const base = s.onlineEndpoint || 'https://api.anthropic.com';
    const r = await withTimeout(fetch(`${base.replace(/\/$/, '')}/v1/messages`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'x-api-key': s.onlineApiKey, 'anthropic-version': '2023-06-01' },
      body: JSON.stringify({ model: s.onlineModel || 'claude-sonnet-4-6', max_tokens: 1024, system, messages: [{ role: 'user', content: user }] }),
    }), 60000);
    if (!r.ok) throw new Error(`Online AI error ${r.status}: ${(await r.text()).slice(0, 200)}`);
    const data: any = await r.json();
    return (data?.content ?? []).map((c: any) => c?.text ?? '').join('').trim();
  }
  // OpenAI-compatible (OpenAI, Azure-compatible, local OpenAI shims, custom).
  const base = s.onlineEndpoint || 'https://api.openai.com';
  const r = await withTimeout(fetch(`${base.replace(/\/$/, '')}/v1/chat/completions`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${s.onlineApiKey}` },
    body: JSON.stringify({ model: s.onlineModel || 'gpt-4o-mini', messages: [{ role: 'system', content: system }, { role: 'user', content: user }] }),
  }), 60000);
  if (!r.ok) throw new Error(`Online AI error ${r.status}: ${(await r.text()).slice(0, 200)}`);
  const data: any = await r.json();
  return data?.choices?.[0]?.message?.content?.trim() ?? '';
}

// Lightweight reachability test for the connection-status badge.
export async function testProvider(s: DennisProviderSettings, which: 'local' | 'online'): Promise<{ ok: boolean; detail: string }> {
  try {
    if (which === 'local') {
      const r = await withTimeout(fetch(`${s.localEndpoint.replace(/\/$/, '')}/api/tags`), 8000);
      return { ok: r.ok, detail: r.ok ? 'Local AI reachable' : `HTTP ${r.status}` };
    }
    const reply = await onlineChat(s, 'You are a connectivity test.', 'Reply with the single word OK.');
    return { ok: !!reply, detail: reply ? 'Online AI reachable' : 'Empty response' };
  } catch (e) {
    return { ok: false, detail: e instanceof Error ? e.message : 'Connection failed' };
  }
}
